// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzL6iDJtmUlYGZLkbhTVlJ-13k9xuFJCE',
    appId: '1:629948825924:web:4f01422c1bbfc2afcd9711',
    messagingSenderId: '629948825924',
    projectId: 'dookanti-a7a10',
    authDomain: 'dookanti-a7a10.firebaseapp.com',
    storageBucket: 'dookanti-a7a10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6-1_s8epsQHsDEuCBCz51GxzSrX1koI',
    appId: '1:629948825924:android:eda0c9e2288a29ffcd9711',
    messagingSenderId: '629948825924',
    projectId: 'dookanti-a7a10',
    storageBucket: 'dookanti-a7a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJIKoHece8q06eDFAruSyyhFvhG54_fQ',
    appId: '1:629948825924:ios:91962eca88c1a217cd9711',
    messagingSenderId: '629948825924',
    projectId: 'dookanti-a7a10',
    storageBucket: 'dookanti-a7a10.appspot.com',
    iosBundleId: 'com.example.dookanti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeJIKoHece8q06eDFAruSyyhFvhG54_fQ',
    appId: '1:629948825924:ios:b34e4a06d03c4300cd9711',
    messagingSenderId: '629948825924',
    projectId: 'dookanti-a7a10',
    storageBucket: 'dookanti-a7a10.appspot.com',
    iosBundleId: 'com.example.dookanti.RunnerTests',
  );
}
